"""add_liveness_challenges

Revision ID: 0cd52f74cb08
Revises: 763bc9ff866d
Create Date: 2026-04-02 01:05:09.415900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd52f74cb08'
down_revision: Union[str, None] = '763bc9ff866d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liveness_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('challenge', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_liveness_challenges_expires_at', 'liveness_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_liveness_challenges_id'), 'liveness_challenges', ['id'], unique=False)
    op.create_index('ix_liveness_challenges_student_id', 'liveness_challenges', ['student_id'], unique=False)
    op.create_index('ix_liveness_challenges_used', 'liveness_challenges', ['used'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_liveness_challenges_used', table_name='liveness_challenges')
    op.drop_index('ix_liveness_challenges_student_id', table_name='liveness_challenges')
    op.drop_index(op.f('ix_liveness_challenges_id'), table_name='liveness_challenges')
    op.drop_index('ix_liveness_challenges_expires_at', table_name='liveness_challenges')
    op.drop_table('liveness_challenges')
    # ### end Alembic commands ###
