"""add_twm_tables_and_timetable_twm_fields

Revision ID: 146dc212aa33
Revises: f83943923f47
Create Date: 2026-04-04 17:35:33.591218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '146dc212aa33'
down_revision: Union[str, None] = 'f83943923f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twm_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'ended', 'expired', name='sessionstatus', create_type=False), nullable=True),
    sa.Column('auto_report_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_twm_sessions_date', 'twm_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_twm_sessions_id'), 'twm_sessions', ['id'], unique=False)
    op.create_index('ix_twm_sessions_tutor_id', 'twm_sessions', ['tutor_id'], unique=False)
    op.create_table('twm_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('present', 'absent', 'late', 'medical_leave', 'duty_leave', name='attendancestatus', create_type=False), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['twm_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_twm_attendance_session_student')
    )
    op.create_index(op.f('ix_twm_attendance_id'), 'twm_attendance', ['id'], unique=False)
    op.create_index('ix_twm_attendance_session_id', 'twm_attendance', ['session_id'], unique=False)
    op.create_index('ix_twm_attendance_student_id', 'twm_attendance', ['student_id'], unique=False)
    op.add_column('timetable', sa.Column('is_twm', sa.Boolean(), nullable=True))
    op.add_column('timetable', sa.Column('tutor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timetable', 'users', ['tutor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_column('timetable', 'tutor_id')
    op.drop_column('timetable', 'is_twm')
    op.drop_index('ix_twm_attendance_student_id', table_name='twm_attendance')
    op.drop_index('ix_twm_attendance_session_id', table_name='twm_attendance')
    op.drop_index(op.f('ix_twm_attendance_id'), table_name='twm_attendance')
    op.drop_table('twm_attendance')
    op.drop_index('ix_twm_sessions_tutor_id', table_name='twm_sessions')
    op.drop_index(op.f('ix_twm_sessions_id'), table_name='twm_sessions')
    op.drop_index('ix_twm_sessions_date', table_name='twm_sessions')
    op.drop_table('twm_sessions')
    # ### end Alembic commands ###
