"""make_timetable_subject_id_nullable

Revision ID: 5aefa9771421
Revises: 146dc212aa33
Create Date: 2026-04-04 17:44:09.447352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aefa9771421'
down_revision: Union[str, None] = '146dc212aa33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('timetable_subject_id_fkey', 'timetable', type_='foreignkey')
    op.create_foreign_key(None, 'timetable', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.create_foreign_key('timetable_subject_id_fkey', 'timetable', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.alter_column('timetable', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
