"""add_totp_fail_face_auth_password_changed_to_users

Revision ID: 763bc9ff866d
Revises: d9826a2178e3
Create Date: 2026-04-02 00:02:41.957837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763bc9ff866d'
down_revision: Union[str, None] = 'd9826a2178e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_fail_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('totp_locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('face_auth_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'face_auth_enabled')
    op.drop_column('users', 'totp_locked_until')
    op.drop_column('users', 'totp_fail_count')
    # ### end Alembic commands ###
