"""initial_schema

Revision ID: 884562e5d779
Revises: 
Create Date: 2026-04-01 14:50:37.454368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884562e5d779'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colleges_id'), 'colleges', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college_id', 'code', name='uq_department_college_code')
    )
    op.create_index('ix_departments_college_id', 'departments', ['college_id'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('duration_years', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'code', name='uq_course_department_code')
    )
    op.create_index('ix_courses_department_id', 'courses', ['department_id'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('principal', 'hod', 'teacher', 'student', name='userrole'), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('azure_person_id', sa.String(length=255), nullable=True),
    sa.Column('face_enrolled', sa.Boolean(), nullable=False),
    sa.Column('face_enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('semester', sa.SmallInteger(), nullable=True),
    sa.Column('parent_phone', sa.String(length=20), nullable=True),
    sa.Column('parent_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_college_id', 'users', ['college_id'], unique=False)
    op.create_index('ix_users_department_id', 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_roll_number'), 'users', ['roll_number'], unique=True)
    op.create_table('alerts_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', 'pending', name='alertstatus'), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'sms', 'email', name='alertchannel'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_log_id'), 'alerts_log', ['id'], unique=False)
    op.create_index('ix_alerts_log_sent_at', 'alerts_log', ['sent_at'], unique=False)
    op.create_index('ix_alerts_log_status', 'alerts_log', ['status'], unique=False)
    op.create_index('ix_alerts_log_student_id', 'alerts_log', ['student_id'], unique=False)
    op.create_table('device_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=500), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_os', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_device_registry_user')
    )
    op.create_index(op.f('ix_device_registry_id'), 'device_registry', ['id'], unique=False)
    op.create_index('ix_device_registry_user_id', 'device_registry', ['user_id'], unique=False)
    op.create_table('face_change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('old_azure_person_id', sa.String(length=255), nullable=True),
    sa.Column('new_azure_person_id', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_change_log_changed_at', 'face_change_log', ['changed_at'], unique=False)
    op.create_index('ix_face_change_log_changed_by', 'face_change_log', ['changed_by'], unique=False)
    op.create_index(op.f('ix_face_change_log_id'), 'face_change_log', ['id'], unique=False)
    op.create_index('ix_face_change_log_student_id', 'face_change_log', ['student_id'], unique=False)
    op.create_table('otp_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('password_reset', 'device_change', 'face_reenroll', 'email_verify', 'phone_verify', name='otppurpose'), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'email', name='otpchannel'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_log_expires_at', 'otp_log', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_log_id'), 'otp_log', ['id'], unique=False)
    op.create_index('ix_otp_log_used', 'otp_log', ['used'], unique=False)
    op.create_index('ix_otp_log_user_id', 'otp_log', ['user_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.SmallInteger(), nullable=False),
    sa.Column('total_lectures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'code', 'semester', name='uq_subject_course_code_semester')
    )
    op.create_index('ix_subjects_course_id', 'subjects', ['course_id'], unique=False)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index('ix_subjects_semester', 'subjects', ['semester'], unique=False)
    op.create_index('ix_subjects_teacher_id', 'subjects', ['teacher_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('active', 'ended', 'expired', name='sessionstatus'), nullable=False),
    sa.Column('teacher_latitude', sa.Float(), nullable=True),
    sa.Column('teacher_longitude', sa.Float(), nullable=True),
    sa.Column('bluetooth_token', sa.String(length=255), nullable=True),
    sa.Column('qr_secret', sa.String(length=255), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('present_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'date', name='uq_attendance_session_subject_date')
    )
    op.create_index('ix_attendance_sessions_date', 'attendance_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_id'), 'attendance_sessions', ['id'], unique=False)
    op.create_index('ix_attendance_sessions_status', 'attendance_sessions', ['status'], unique=False)
    op.create_index('ix_attendance_sessions_subject_id', 'attendance_sessions', ['subject_id'], unique=False)
    op.create_index('ix_attendance_sessions_teacher_id', 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_table('timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'day_of_week', 'start_time', name='uq_timetable_subject_day_start')
    )
    op.create_index('ix_timetable_day_of_week', 'timetable', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_timetable_id'), 'timetable', ['id'], unique=False)
    op.create_index('ix_timetable_subject_id', 'timetable', ['subject_id'], unique=False)
    op.create_index('ix_timetable_teacher_id', 'timetable', ['teacher_id'], unique=False)
    op.create_table('attendance_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.Enum('success', 'failed', name='auditresult'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('face_confidence', sa.Float(), nullable=True),
    sa.Column('gps_distance_meters', sa.Float(), nullable=True),
    sa.Column('bluetooth_detected', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_audit_attempt_at', 'attendance_audit', ['attempt_at'], unique=False)
    op.create_index(op.f('ix_attendance_audit_id'), 'attendance_audit', ['id'], unique=False)
    op.create_index('ix_attendance_audit_result', 'attendance_audit', ['result'], unique=False)
    op.create_index('ix_attendance_audit_session_id', 'attendance_audit', ['session_id'], unique=False)
    op.create_index('ix_attendance_audit_student_id', 'attendance_audit', ['student_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'medical_leave', 'duty_leave', name='attendancestatus'), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('marked_by', sa.Enum('qr_scan', 'manual', 'auto_absent', name='markedby'), nullable=False),
    sa.Column('face_verified', sa.Boolean(), nullable=False),
    sa.Column('gps_verified', sa.Boolean(), nullable=False),
    sa.Column('bluetooth_verified', sa.Boolean(), nullable=False),
    sa.Column('student_latitude', sa.Float(), nullable=True),
    sa.Column('student_longitude', sa.Float(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_attendance_record_session_student')
    )
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index('ix_attendance_records_marked_at', 'attendance_records', ['marked_at'], unique=False)
    op.create_index('ix_attendance_records_session_id', 'attendance_records', ['session_id'], unique=False)
    op.create_index('ix_attendance_records_status', 'attendance_records', ['status'], unique=False)
    op.create_index('ix_attendance_records_student_id', 'attendance_records', ['student_id'], unique=False)
    op.create_table('face_verify_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_face_verify_tokens_expires_at', 'face_verify_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_face_verify_tokens_id'), 'face_verify_tokens', ['id'], unique=False)
    op.create_index('ix_face_verify_tokens_session_id', 'face_verify_tokens', ['session_id'], unique=False)
    op.create_index('ix_face_verify_tokens_used', 'face_verify_tokens', ['used'], unique=False)
    op.create_index('ix_face_verify_tokens_user_id', 'face_verify_tokens', ['user_id'], unique=False)
    op.create_table('qr_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('time_slot', sa.BigInteger(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'time_slot', name='uq_qr_token_session_timeslot')
    )
    op.create_index(op.f('ix_qr_tokens_id'), 'qr_tokens', ['id'], unique=False)
    op.create_index('ix_qr_tokens_is_used', 'qr_tokens', ['is_used'], unique=False)
    op.create_index('ix_qr_tokens_session_id', 'qr_tokens', ['session_id'], unique=False)
    op.create_index('ix_qr_tokens_time_slot', 'qr_tokens', ['time_slot'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qr_tokens_time_slot', table_name='qr_tokens')
    op.drop_index('ix_qr_tokens_session_id', table_name='qr_tokens')
    op.drop_index('ix_qr_tokens_is_used', table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_id'), table_name='qr_tokens')
    op.drop_table('qr_tokens')
    op.drop_index('ix_face_verify_tokens_user_id', table_name='face_verify_tokens')
    op.drop_index('ix_face_verify_tokens_used', table_name='face_verify_tokens')
    op.drop_index('ix_face_verify_tokens_session_id', table_name='face_verify_tokens')
    op.drop_index(op.f('ix_face_verify_tokens_id'), table_name='face_verify_tokens')
    op.drop_index('ix_face_verify_tokens_expires_at', table_name='face_verify_tokens')
    op.drop_table('face_verify_tokens')
    op.drop_index('ix_attendance_records_student_id', table_name='attendance_records')
    op.drop_index('ix_attendance_records_status', table_name='attendance_records')
    op.drop_index('ix_attendance_records_session_id', table_name='attendance_records')
    op.drop_index('ix_attendance_records_marked_at', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('ix_attendance_audit_student_id', table_name='attendance_audit')
    op.drop_index('ix_attendance_audit_session_id', table_name='attendance_audit')
    op.drop_index('ix_attendance_audit_result', table_name='attendance_audit')
    op.drop_index(op.f('ix_attendance_audit_id'), table_name='attendance_audit')
    op.drop_index('ix_attendance_audit_attempt_at', table_name='attendance_audit')
    op.drop_table('attendance_audit')
    op.drop_index('ix_timetable_teacher_id', table_name='timetable')
    op.drop_index('ix_timetable_subject_id', table_name='timetable')
    op.drop_index(op.f('ix_timetable_id'), table_name='timetable')
    op.drop_index('ix_timetable_day_of_week', table_name='timetable')
    op.drop_table('timetable')
    op.drop_index('ix_attendance_sessions_teacher_id', table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_subject_id', table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_status', table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_id'), table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_date', table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index('ix_subjects_teacher_id', table_name='subjects')
    op.drop_index('ix_subjects_semester', table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index('ix_subjects_course_id', table_name='subjects')
    op.drop_table('subjects')
    op.drop_index('ix_otp_log_user_id', table_name='otp_log')
    op.drop_index('ix_otp_log_used', table_name='otp_log')
    op.drop_index(op.f('ix_otp_log_id'), table_name='otp_log')
    op.drop_index('ix_otp_log_expires_at', table_name='otp_log')
    op.drop_table('otp_log')
    op.drop_index('ix_face_change_log_student_id', table_name='face_change_log')
    op.drop_index(op.f('ix_face_change_log_id'), table_name='face_change_log')
    op.drop_index('ix_face_change_log_changed_by', table_name='face_change_log')
    op.drop_index('ix_face_change_log_changed_at', table_name='face_change_log')
    op.drop_table('face_change_log')
    op.drop_index('ix_device_registry_user_id', table_name='device_registry')
    op.drop_index(op.f('ix_device_registry_id'), table_name='device_registry')
    op.drop_table('device_registry')
    op.drop_index('ix_alerts_log_student_id', table_name='alerts_log')
    op.drop_index('ix_alerts_log_status', table_name='alerts_log')
    op.drop_index('ix_alerts_log_sent_at', table_name='alerts_log')
    op.drop_index(op.f('ix_alerts_log_id'), table_name='alerts_log')
    op.drop_table('alerts_log')
    op.drop_index(op.f('ix_users_roll_number'), table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_department_id', table_name='users')
    op.drop_index('ix_users_college_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index('ix_courses_department_id', table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index('ix_departments_college_id', table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_colleges_id'), table_name='colleges')
    op.drop_table('colleges')
    # ### end Alembic commands ###
