"""add_tutor_assignments_table

Revision ID: c2fd57929a4e
Revises: d41893ca7a10
Create Date: 2026-04-04 16:28:41.731880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2fd57929a4e'
down_revision: Union[str, None] = 'd41893ca7a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_year', name='uq_student_tutor_year')
    )
    op.create_index('ix_tutor_assignments_academic_year', 'tutor_assignments', ['academic_year'], unique=False)
    op.create_index(op.f('ix_tutor_assignments_id'), 'tutor_assignments', ['id'], unique=False)
    op.create_index('ix_tutor_assignments_student_id', 'tutor_assignments', ['student_id'], unique=False)
    op.create_index('ix_tutor_assignments_tutor_id', 'tutor_assignments', ['tutor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tutor_assignments_tutor_id', table_name='tutor_assignments')
    op.drop_index('ix_tutor_assignments_student_id', table_name='tutor_assignments')
    op.drop_index(op.f('ix_tutor_assignments_id'), table_name='tutor_assignments')
    op.drop_index('ix_tutor_assignments_academic_year', table_name='tutor_assignments')
    op.drop_table('tutor_assignments')
    # ### end Alembic commands ###
