"""add_sections_table_and_section_id_fks

Revision ID: d41893ca7a10
Revises: 0a4164c8f7c5
Create Date: 2026-04-04 16:15:00.306251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41893ca7a10'
down_revision: Union[str, None] = '0a4164c8f7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('max_strength', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'semester', 'name', name='uq_section_course_semester_name')
    )
    op.create_index('ix_sections_course_id', 'sections', ['course_id'], unique=False)
    op.create_index('ix_sections_department_id', 'sections', ['department_id'], unique=False)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.add_column('attendance_sessions', sa.Column('section_id', sa.Integer(), nullable=True))
    op.drop_constraint('uq_attendance_session_subject_date', 'attendance_sessions', type_='unique')
    op.create_index('ix_attendance_sessions_section_id', 'attendance_sessions', ['section_id'], unique=False)
    op.create_unique_constraint('uq_attendance_session_subject_date_section', 'attendance_sessions', ['subject_id', 'date', 'section_id'])
    op.create_foreign_key(None, 'attendance_sessions', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'section_id')
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_constraint('uq_attendance_session_subject_date_section', 'attendance_sessions', type_='unique')
    op.drop_index('ix_attendance_sessions_section_id', table_name='attendance_sessions')
    op.create_unique_constraint('uq_attendance_session_subject_date', 'attendance_sessions', ['subject_id', 'date'])
    op.drop_column('attendance_sessions', 'section_id')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_index('ix_sections_department_id', table_name='sections')
    op.drop_index('ix_sections_course_id', table_name='sections')
    op.drop_table('sections')
    # ### end Alembic commands ###
