"""add_timetable_section_period_lab_color

Revision ID: f83943923f47
Revises: c2fd57929a4e
Create Date: 2026-04-04 17:09:37.775655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83943923f47'
down_revision: Union[str, None] = 'c2fd57929a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('section_id', sa.Integer(), nullable=True))
    op.add_column('timetable', sa.Column('period_number', sa.SmallInteger(), nullable=True))
    op.add_column('timetable', sa.Column('is_lab', sa.Boolean(), nullable=True))
    op.add_column('timetable', sa.Column('color_tag', sa.String(length=20), nullable=True))
    op.create_index('ix_timetable_section_id', 'timetable', ['section_id'], unique=False)
    op.create_foreign_key(None, 'timetable', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_index('ix_timetable_section_id', table_name='timetable')
    op.drop_column('timetable', 'color_tag')
    op.drop_column('timetable', 'is_lab')
    op.drop_column('timetable', 'period_number')
    op.drop_column('timetable', 'section_id')
    # ### end Alembic commands ###
